### ISSUE TITLE
LSP can't autocomplete for provider "google"

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/tf-ncl#49] opened 2023-05-01 11:16 UTC
Using the template provided with the TF provider `github` has autocomplete working.
But with TF provider `google` autocomplete does not work.

```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    nickel.url = "github:tweag/nickel";
    tf-ncl.url = "github:tweag/tf-ncl";
    tf-ncl.inputs.nickel.follows = "nickel";
    utils.url = "github:numtide/flake-utils";
  };

  nixConfig = {
    extra-substituters = [ "https://tweag-nickel.cachix.org" ];
    extra-trusted-public-keys = [ "tweag-nickel.cachix.org-1:GIthuiK4LRgnW64ALYEoioVUQBWs0jexyoYVeLDBwRA=" ];
  };

  outputs = inputs: inputs.utils.lib.eachDefaultSystem (system:
    {
      devShell = inputs.tf-ncl.lib.${system}.mkDevShell {
        providers = p: {
          inherit (p) github;
        };
      };
    });
}

```
![image](https://user-images.githubusercontent.com/1882000/235444533-668cf3da-66da-42b6-b00a-a578edcdbe73.png)

```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-unstable";
    nickel.url = "github:tweag/nickel";
    tf-ncl.url = "github:tweag/tf-ncl";
    tf-ncl.inputs.nickel.follows = "nickel";
    utils.url = "github:numtide/flake-utils";
  };

  nixConfig = {
    extra-substituters = [ "https://tweag-nickel.cachix.org" ];
    extra-trusted-public-keys = [ "tweag-nickel.cachix.org-1:GIthuiK4LRgnW64ALYEoioVUQBWs0jexyoYVeLDBwRA=" ];
  };

  outputs = inputs: inputs.utils.lib.eachDefaultSystem (system:
    {
      devShell = inputs.tf-ncl.lib.${system}.mkDevShell {
        providers = p: {
          inherit (p) google;
        };
      };
    });
}
```

![image](https://user-images.githubusercontent.com/1882000/235444595-200276cb-1e0a-400e-8e12-d9772bd59f61.png)

Note: don't forget to run `link-schema` in between

**Comment by vkleen** [comment] 2023-05-02 10:53
Thanks for the detailed report! I'm fairly confident that the issue is the language server just taking too long to process the completion request for the `google` provider contract, on account of its size. The best solution to that would be a project that I was contemplating anyway, namely to try modularizing the generated contracts. It might be feasible to replace the current monolithic contract file with one that essentially just lists all the available resources or data source with `import` statements for the actualy contract for each. That would at least push the timeout limit further down the road.

**Comment by GuillaumeDesforges** [comment] 2023-05-02 13:27
@vkleen thanks for the fast reply

> the issue is the language server just taking too long to process the completion request for the google provider contract, on account of its size

I came to the same conclusions as well. For the record, I use `coc.nvim`.

> modularizing the generated contracts

Sounds very interesting. :slightly_smiling_face:

**Comment by sedlund** [comment] 2024-03-19 08:03
i tried this example with the github provider and found that the nls language server process climbed up to 5gb of used ram while trying different completions and it oom'd my VM i was running it on.   is the ram usage expected?  if so how much ram should i plan to have to work with this?

**Comment by yannham** [comment] 2024-03-20 17:10
Hi @sedlund, thanks for the report. 5GB isn't reasonable, no. Could you tell what version of `nls` did you install? Because of a dumb overlook, `nls` doesn't have a `--version` argument available, but if you installed it with a `nickel` binary, then `nickel --version` should do the trick.

**Comment by sedlund** [comment] 2024-03-21 10:50
didnt want to hijack this - opened #66

**Comment by yannham** [comment] 2024-12-26 11:37
@jneem I believe this has been fixed by https://github.com/tweag/nickel/pull/2073?

**Comment by yannham** [comment] 2024-12-26 14:34
Great, let's close - feel free to ask to re-open if this isn't the case in your experience.

**Closed by yannham** 2024-12-26 14:34 UTC
